# Generated by Django 4.2.1 on 2024-07-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('assign_date', models.DateField()),
                ('category', models.ManyToManyField(related_name='categories', to='category.taskcategory')),
            ],
        ),
    ]
