# Generated by Django 4.2.1 on 2024-07-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
